### ISSUE TITLE
Integrate a CI to test new features automatically 

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-media-service#35]
Make the tests start automatically when a new PR is made, like it is the case in other repos.

1. To start, create a folder `.github` and the subfolder `workflows`
2. Add a file called for example `continuous_integration.yml`
3. The scaffold of this file looks something like the following:
```yml
name: <a name>

on: [ push, pull_request ]

env:
  PYTHON_VERSION: <python version>

jobs:
  <a job name>:
    name: <a more descriptive name>
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make run-tests
    - name: Stop containers
      run: make stop-tests
```

It is necessary, that at least the make target `run-tests` will be executed.
